### ISSUE TITLE
Missing tag: `release/melodic/psen_scan_v2/0.1.6-1`

### ISSUE THREAD

**Issue by lopsided98** [PilzDE/psen_scan_v2-release#1]
It looks like you deleted the `release/melodic/psen_scan_v2/0.1.6-1` tag, but it is still referenced in rosdistro. You should either restore the tag or remove the release from rosdistro.

**Comment by agutenkunst** [comment]
Thanks for the notification! Should be resolved by https://github.com/ros/rosdistro/pull/29282

**Comment by lopsided98** [comment]
Thanks!

**Comment by clalancette** [comment]
In general, it is a very bad idea to remove existing tags.  You don't know what downstream things are going to be relying on them.  For instance, our rosdistro CI is now breaking because the old tag is still cached.  I think that will eventually resolve itself, but it is still causing problems right now.

In the future, please just leave existing tags in place when doing new releases.

**Comment by agutenkunst** [comment]
@clalancette A bit of background on this:
We had to restart the release repo since somehow dangling commits developed and where causing issues when trying to `bloom-release`. We were not able to retrace or resolve the situation.

**Comment by clalancette** [comment]
> We had to restart the release repo since somehow dangling commits developed and where causing issues when trying to `bloom-release`. We were not able to retrace or resolve the situation.

Thanks for explaining the situation.  It looks like things are resolved now, so I think this can be closed out.
